#!/bin/bash

outname=$2
outname=$(echo ${outname%.*})
outname=$(echo $outname | awk '{print toupper($0)}')
echo "#ifndef "$outname"_H" > $2
echo "#define "$outname"_H

/**
 *********************************************************************************
 *********************************************************************************
  WARNING THIS IS AN AUTOGENERATED FILE!!!
  Do not modify this file, but edit the:
  $1 file 
  and then run: 
  ./generate_grammar_header.sh $1 $2
 *********************************************************************************
 *********************************************************************************
 **/
 
#include \"mpc/mpc.h\"

" >> $2

echo "#define X_MACRO_PARSE_VARS\\" >> $2

linecount=$(wc -l < "$1")
i=0
while IFS='' read -r line || [[ -n "$line" ]]; do
    #echo "$line"
    var=$(echo "$line" | sed -re 's/([^[:space:]]*)\s*\:.*/\1/g')
    string=$var
    if [ "$var" = "float" ]; then
        var=$var"_"
    fi
    i=$((i+1))
    if [ $i -eq $linecount ]; 
    then
        echo "  X($var, \"$string\")" >> $2
    else 
        echo "  X($var, \"$string\")\\" >> $2
    fi
done < "$1"
echo "#endif" >> $2
