#ifndef LEGACY_SYMBOLLIB_GRAMMAR_H
#define LEGACY_SYMBOLLIB_GRAMMAR_H

/**
 *********************************************************************************
 *********************************************************************************
  WARNING THIS IS AN AUTOGENERATED FILE!!!
  Do not modify this file, but edit the:
  symbollib_grammar.txt file 
  and then run: 
  ./generate_grammar_header.sh symbollib_grammar.txt legacy_symbollib_grammar.h
 *********************************************************************************
 *********************************************************************************
 **/
 
#include "mpc/mpc.h"


#define X_MACRO_PARSE_VARS\
  X(s, "s")\
  X(n, "n")\
  X(sign, "sign")\
  X(string, "string")\
  X(nonquoted_string, "nonquoted_string")\
  X(nonquoted_name_string, "nonquoted_name_string")\
  X(integer, "integer")\
  X(hexint, "hexint")\
  X(x, "x")\
  X(y, "y")\
  X(float_, "float")\
  X(header, "header")\
  X(encoding, "encoding")\
  X(symbol, "symbol")\
  X(fplist, "fplist")\
  X(fpalias, "fpalias")\
  X(drawing, "drawing")\
  X(symboldef, "symboldef")\
  X(symbolname, "symbolname")\
  X(prefix, "prefix")\
  X(pin_name_offset, "pin_name_offset")\
  X(show_pin_numbers, "show_pin_numbers")\
  X(show_pin_names, "show_pin_names")\
  X(number_of_parts, "number_of_parts")\
  X(is_locked, "is_locked")\
  X(is_power, "is_power")\
  X(size, "size")\
  X(orientation, "orientation")\
  X(visible, "visible")\
  X(halign, "halign")\
  X(valign, "valign")\
  X(italic, "italic")\
  X(bold, "bold")\
  X(refdes_text, "refdes_text")\
  X(name_text, "name_text")\
  X(footprint_text, "footprint_text")\
  X(datasheet_text, "datasheet_text")\
  X(user_text, "user_text")\
  X(aliases, "aliases")\
  X(arc, "arc")\
  X(radius, "radius")\
  X(start_angle, "start_angle")\
  X(end_angle, "end_angle")\
  X(part_index, "part_index")\
  X(dmg, "dmg")\
  X(pen, "pen")\
  X(fill, "fill")\
  X(xstart, "xstart")\
  X(ystart, "ystart")\
  X(xend, "xend")\
  X(yend, "yend")\
  X(circle, "circle")\
  X(polygon, "polygon")\
  X(points, "points")\
  X(point, "point")\
  X(count, "count")\
  X(rectangle, "rectangle")\
  X(x1, "x1")\
  X(y1, "y1")\
  X(x2, "x2")\
  X(y2, "y2")\
  X(italic_text, "italic_text")\
  X(bold_text, "bold_text")\
  X(text, "text")\
  X(hidden, "hidden")\
  X(angle, "angle")\
  X(bezier, "bezier")\
  X(pin, "pin")\
  X(pin_number, "pin_number")\
  X(name, "name")\
  X(length, "length")\
  X(pin_orientation, "pin_orientation")\
  X(pin_num_size, "pin_num_size")\
  X(pin_name_size, "pin_name_size")\
  X(pin_type, "pin_type")\
  X(pin_shape, "pin_shape")\
  X(comment, "comment")\
  X(anyline, "anyline")\
  X(symbol_lib, "symbol_lib")
#endif
